### ISSUE TITLE
Hi! What about GNU/Linux support?

### ISSUE THREAD

**Issue by Kerrung** [jeremy-jr-benthum/tor-button#6]
Hi! What about GNU/Linux support?

**Comment by Kerrung** [comment]
https://wiki.archlinux.org/index.php/Tor
It works with this. Thank you.

**Comment by F1uk369** [comment]
I've added a pull request for a Linux support patch I made, however in the meantime, use my repository: https://github.com/F1uk369/onion-browser-button
